/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SampleAlertRouteImport } from './routes/sample-alert'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ImportBasicsRouteImport } from './routes/import-basics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsIdRouteImport } from './routes/alerts.$id'

const SampleAlertRoute = SampleAlertRouteImport.update({
  id: '/sample-alert',
  path: '/sample-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportBasicsRoute = ImportBasicsRouteImport.update({
  id: '/import-basics',
  path: '/import-basics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/alerts/$id',
  path: '/alerts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/import-basics': typeof ImportBasicsRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/sample-alert': typeof SampleAlertRoute
  '/alerts/$id': typeof AlertsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/import-basics': typeof ImportBasicsRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/sample-alert': typeof SampleAlertRoute
  '/alerts/$id': typeof AlertsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/import-basics': typeof ImportBasicsRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/sample-alert': typeof SampleAlertRoute
  '/alerts/$id': typeof AlertsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/dashboard'
    | '/import-basics'
    | '/onboarding'
    | '/preferences'
    | '/pricing'
    | '/products'
    | '/sample-alert'
    | '/alerts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/dashboard'
    | '/import-basics'
    | '/onboarding'
    | '/preferences'
    | '/pricing'
    | '/products'
    | '/sample-alert'
    | '/alerts/$id'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/dashboard'
    | '/import-basics'
    | '/onboarding'
    | '/preferences'
    | '/pricing'
    | '/products'
    | '/sample-alert'
    | '/alerts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  DashboardRoute: typeof DashboardRoute
  ImportBasicsRoute: typeof ImportBasicsRoute
  OnboardingRoute: typeof OnboardingRoute
  PreferencesRoute: typeof PreferencesRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  SampleAlertRoute: typeof SampleAlertRoute
  AlertsIdRoute: typeof AlertsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sample-alert': {
      id: '/sample-alert'
      path: '/sample-alert'
      fullPath: '/sample-alert'
      preLoaderRoute: typeof SampleAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-basics': {
      id: '/import-basics'
      path: '/import-basics'
      fullPath: '/import-basics'
      preLoaderRoute: typeof ImportBasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/alerts/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  DashboardRoute: DashboardRoute,
  ImportBasicsRoute: ImportBasicsRoute,
  OnboardingRoute: OnboardingRoute,
  PreferencesRoute: PreferencesRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  SampleAlertRoute: SampleAlertRoute,
  AlertsIdRoute: AlertsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
